name: Update Ansible Templates

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  update-template-and-create-pr:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: '**/requirements.txt'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set Environment Date Key
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Set Environment Branch Name
        run: echo "NEW_BRANCH=auto-update-templates" >> $GITHUB_ENV

      - name: Create New Branch from Master
        run: |
          git fetch origin
          git checkout -b "$NEW_BRANCH" 2>/dev/null || git checkout "$NEW_BRANCH"

      - name: Update Project
        if: success()
        run: python ./scripts/update.py --update-readme --update-directories

      - name: Commit and Push Changes
        if: success()
        run: bash ./.github/deployment/commit_and_push.sh

      - name: Fetch branches
        run: git fetch origin

      - name: Check for Existing Pull Request
        if: success()
        id: check-pr
        env:
          NEW_BRANCH: ${{ env.NEW_BRANCH }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bash ./.github/deployment/check_for_existing_pr.sh

      - name: Create Pull Request
        if: success()
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Update Ansible Project Structure to Latest Guidelines [${{ env.DATE }}]"
          body: |
            This automated PR updates the `ansible-template-skeletons` project directory structure to align with the latest official Ansible documentation as of ${{ env.DATE }}.

            ### Changes Included:
            - Updated templates to reflect the latest documentation standards.

            For more details, please review the included changes.
          base: "master"  # This is the base branch you want to merge your PR into
          branch: ${{ env.NEW_BRANCH }}  # This is the source branch from which the PR is created
          assignees: ${{ github.actor }}  # This assigns the PR to the user who triggered the action
          reviewers: ${{ github.actor }}
          labels: auto-update,template-change,needs-review
